dist: bionic
language: python # 默认是ruby
python: 3.7

install:
  # nuo主题需要extended版本的hugo，其他主题可以用最新的普通版本就行
  - wget https://github.com/gohugoio/hugo/releases/download/v0.62.2/hugo_0.62.2_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

# before_script:
#   - rm -rf ./public
#   - git submodule init
#   - git submodule update

script:
  - hugo

# after_script:
#   - cd ./public
#   - git add .
#   - git commit -m "feat:update by travis ci"
#   - git push origin HEAD:master

# 构建完成后会自动更新Github Pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: src