# This is a basic workflow to help you get started with Actions

name: Python package

on:
  push:
    branches: [ src ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Hugo Actions
        uses: srt32/hugo-action@v0.0.3
