# This is a basic workflow to help you get started with Actions
name: Hugo Deploy

on:
  push:
    branches: [ src ]


jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Build 
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.hugo_token}} 
          PUBLISH_BRANCH: master 
          PUBLISH_DIR: ./public  
          commit_message: CI Auto Deploy
