# This is a basic workflow to help you get started with Actions

name: Hugo Deploy

on:
  push:
    branches: [ src ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Hugo Actions
        uses: srt32/hugo-action@v0.0.3

      - name: Build 
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.hugo_token}} 
          PUBLISH_BRANCH: master 
          PUBLISH_DIR: ./public  
          commit_message: Auto Deploy
